// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package example

import (
	"github.com/oldsaltedfish/wireprovider/config"
	"github.com/oldsaltedfish/wireprovider/kafka"
	"github.com/oldsaltedfish/wireprovider/logger"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp() (*App, error) {
	configConfig := config.NewConfig()
	logfLogger := logger.NewLogger(configConfig)
	asyncProducer, err := kafka.NewAsyncProducer(configConfig, logfLogger)
	if err != nil {
		return nil, err
	}
	syncProducer, err := kafka.NewSyncProducer(configConfig, logfLogger)
	if err != nil {
		return nil, err
	}
	app := NewApp(logfLogger, asyncProducer, syncProducer, configConfig)
	return app, nil
}
