// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package example

import (
	"github.com/oldsaltedfish/wireprovider/config"
	"github.com/oldsaltedfish/wireprovider/database"
	gorm2 "github.com/oldsaltedfish/wireprovider/gorm"
	"github.com/oldsaltedfish/wireprovider/logger"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func wireDB() (*gorm.DB, error) {
	configConfig := config.NewConfig()
	logfLogger := logger.NewLogger(configConfig)
	db, err := database.New(configConfig, logfLogger)
	if err != nil {
		return nil, err
	}
	gormDB, err := gorm2.New(db, configConfig, logfLogger)
	if err != nil {
		return nil, err
	}
	return gormDB, nil
}
