// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package example

import (
	"github.com/oldsaltedfish/wireprovider/config"
	"github.com/oldsaltedfish/wireprovider/logger"
	redis2 "github.com/oldsaltedfish/wireprovider/redis"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func wireRedis() (redis.Cmdable, error) {
	configConfig := config.NewConfig()
	logfLogger := logger.NewLogger(configConfig)
	cmdable, err := redis2.NewClient(configConfig, logfLogger)
	if err != nil {
		return nil, err
	}
	return cmdable, nil
}
