// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package example

import (
	"github.com/oldsaltedfish/wireprovider/config"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireConfig() *wireconfig.Config {
	config := wireconfig.NewConfig()
	return config
}
